version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:6.0  # Certifique-se de usar o prefixo docker.io para imagens do Docker Hub
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
